### ISSUE TITLE
crashes on startup server fabric(1.14.4-165)nice-to-have-1.2.0) Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin 

### ISSUE THREAD

**Issue by SDUBZ** [RedstoneParadox/NiceToHave#11]
nice-to-have-1.2.0

http://puu.sh/Efb2H/1ef3870597.txt
server log
http://puu.sh/Efb2B/0984c9ff0c.log

**Comment by RedstoneParadox** [comment]
This has happened before and I'm not entirely sure how to fix it.

Just to be sure it's not loader, could you please try to download a fresh install of Fabric Loader off of the website and see if that fixes it?

**Comment by SDUBZ** [comment]
have tried no change

**Comment by RedstoneParadox** [comment]
Sorry for the delay; this should be fixed in 1.2.1. Please let me know if it is or if the issue persists.
