### ISSUE TITLE
java.lang.ClassNotFoundException: net/minecraft/resource/NamespaceResourceManager

### ISSUE THREAD

**Issue by matthijsvdmeulen** [RedstoneParadox/NiceToHave#14]
Nice to Have version:
nice-to-have-1.3.0-beta.1

Fabric Loader Version:
0.7.2+build.174

Fabric API Version:
fabric-api-0.4.23+build.276-1.15

Fabric Language Kotlin Version:
fabric-language-kotlin-1.3.50+build.1

Name and version of any other mods present:
Happens with all other mods removed

What actually happened:
Client crashed before launching minecraft

Steps to reproduce:
launch instance with fabric, kotlin and nice to have

Crashlog:
https://paste.ee/p/Srslr

**Comment by RedstoneParadox** [comment]
Try updating fabric language kotlin to `1.3.60+build.1`; it probably won't help, but just to make sure.

**Comment by RedstoneParadox** [comment]
This should be fixed in 1.3.0-beta.2; Please let me know if it isn't.
