### ISSUE TITLE
1.15.1(crash on load)

### ISSUE THREAD

**Issue by SDUBZ** [RedstoneParadox/NiceToHave#16]
https://paste.ee/p/22sUU
nice-to-have-1.3.0-beta.2
loader: 0.7.4-177
fabric-api-0.4.27+build.286-1.15

**Comment by RedstoneParadox** [comment]
Is this still an issue?

**Comment by SDUBZ** [comment]
im not sure anymore been busy working with 1.15.2

**Comment by RedstoneParadox** [comment]
This appears to have been fixed in 1.3.0-beta.3.
