### ISSUE TITLE
1.15.2 problems joining server

### ISSUE THREAD

**Issue by SDUBZ** [RedstoneParadox/NiceToHave#17]
https://cdn.discordapp.com/attachments/608088354042544139/678564785670848513/unknown.png

nice-to-have-1.3.0-beta.4.jar both on server and client

fabric loader - 0.7.8-184
fabric api fabric-api-0.4.32+build.292-1.15

**Comment by RedstoneParadox** [comment]
You can currently work around this by joining a single-player world before joining multiplayer as it helps the tags load in properly.

**Comment by RedstoneParadox** [comment]
This is now fixed in 1.3.0 Beta 5
