### ISSUE TITLE
Unable to log into server due to failure in reading paint recipe

### ISSUE THREAD

**Issue by tacogerbil** [RedstoneParadox/NiceToHave#19]
**Nice to Have version:** nice-to-have-1.3.3

**Fabric Loader Version:** 0.10.6 + 0.214

**Fabric API Version:** fabric-api-0.25.1+build.416-1.16

**Fabric Language Kotlin Version:** fabric-language-kotlin-1.4.0+build.1

**Name and versions of any other mods present:** https://pastebin.com/vVJdrN6e

**What happened:** Tried logging into my server and received 
Internal Exception: io.netty.handler.codec.DecoderException:
com.google.gson.JsonSyntaxException: Failed while reading paint recipe nicetohave:paint_carpet!

![image](https://user-images.githubusercontent.com/12961907/98067063-92b9f280-1e0d-11eb-83e9-461a5304c9d8.png)

**Steps to reproduce:**

**Comment by RedstoneParadox** [comment]
Fixed in version 1.3.4
