### ISSUE TITLE
Printing Hello World to the log

### ISSUE THREAD

**Issue by coderbot16** [RedstoneParadox/NiceToHave#2]
Looks like this mod is printing debug "Hello World" messages to the log.

* https://github.com/RedstoneParadox/NiceToHave/blob/master/src/main/java/net/redstoneparadox/nicetohave/NiceToHave.kt#L20
* https://github.com/RedstoneParadox/NiceToHave/blob/master/src/main/java/net/redstoneparadox/nicetohave/client/NiceToHaveClient.kt#L12

**Comment by RedstoneParadox** [comment]
I'm aware.

**Comment by coderbot16** [comment]
Is this intended? It's quite annoying in the context of a modpack especially when there's no indication what mod this comes from.

**Comment by RedstoneParadox** [comment]
It's simply leftover code from pre-release that I haven't gotten around to cleaning up yet.

**Comment by Prospector** [comment]
usually a closed issue means it is resolved...

**Comment by RedstoneParadox** [comment]
Resolved in 1.0.2.
