### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by calloatti** [RedstoneParadox/NiceToHave#3]
**Nice to Have version:**
nice-to-have-1.0.1

**Fabric Loader Version:**
Latest

**Fabric API Version:**
fabric-api-0.3.0+build.207

**Fabric Language Kotlin Version:**
fabric-language-kotlin-1.3.40+build.1

**Name and version of any other mods present:**

**What actually happened:**
server crash

**Steps to reproduce:**
Setup a mc/fabric server with the 3 jars in the mod folder

https://paste.ee/p/IZ7EK

**Comment by RedstoneParadox** [comment]
Fixed as of release 1.0.2.

**Comment by whatname13** [comment]
I think this bug reappeared in nice-to-have-1.0.3 because this just happened to me and I identified this mod to be the problem.

**Comment by RedstoneParadox** [comment]
Found and fixed the issue @whatname13 . The fix will be released in version 1.1.0 (unless a ton of urgent issues crop up, then I'll make a 1.0.4 release).
